name: hundetage
description: Eine App fÃ¼r interaktive Kindergeschichten.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  cupertino_icons:

flutter:
  uses-material-design: true
  assets:
  - images/icon.png
  - images/user_screen_top_image.png
  - images/user_images/hund_0.jpg
  - images/user_images/hund_1.jpg
  - images/user_images/hund_2.jpg
  - images/user_images/hund_3.jpg
  - images/user_images/hund_4.jpg
  - images/user_images/hund_5.jpg
  - images/user_images/hund_6.jpg
  - images/user_images/hund_7.jpg