name: hundetage
description: Eine App fÃ¼r interaktive Kindergeschichten.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev.0.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.5+2
  firebase_analytics: ^3.0.3
  connectivity: ^0.4.3+2
  path_provider: ^1.1.0
  image_picker: ^0.6.0+10
  firebase_performance: 0.3.0+1
  http: ^0.12.0+2

dev_dependencies:
  image_test_utils: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito:

flutter:
  uses-material-design: true
  fonts:
    - family: IndieFlower
      fonts:
        - asset: assets/IndieFlower.ttf
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
          style: normal
        - asset: assets/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/Montserrat-Italic.ttf
          style: italic
        - asset: assets/Montserrat-BoldItalic.ttf
          style: italic
          weight: 600

  assets:
    - assets/images/forward.png
    - assets/images/jakob_lukas.png
    - assets/images/jakob.png
    - assets/images/lukas.png
    - assets/images/user_images/gender_selection/girl-0.png
    - assets/images/user_images/gender_selection/girl-1.png
    - assets/images/user_images/gender_selection/girl-2.png
    - assets/images/user_images/gender_selection/girl-3.png
    - assets/images/user_images/gender_selection/girl-4.png
    - assets/images/user_images/gender_selection/girl-5.png
    - assets/images/user_images/gender_selection/girl-6.png
    - assets/images/user_images/gender_selection/girl-7.png
    - assets/images/user_images/gender_selection/girl-8.png
    - assets/images/user_images/gender_selection/girl-9.png
    - assets/images/user_images/gender_selection/girl-10.png
    - assets/images/user_images/gender_selection/girl-11.png
    - assets/images/user_images/gender_selection/boy-0.png
    - assets/images/user_images/gender_selection/boy-1.png
    - assets/images/user_images/gender_selection/boy-2.png
    - assets/images/user_images/gender_selection/boy-3.png
    - assets/images/user_images/gender_selection/boy-4.png
    - assets/images/user_images/gender_selection/boy-5.png
    - assets/images/user_images/gender_selection/boy-6.png
    - assets/images/user_images/gender_selection/boy-7.png
    - assets/images/user_images/gender_selection/boy-8.png
    - assets/images/user_images/gender_selection/boy-9.png
    - assets/images/user_images/gender_selection/boy-10.png
    - assets/images/user_images/gender_selection/boy-11.png
    - assets/images/icon.png
    - assets/images/event.png

