name: hundetage
description: Eine App fÃ¼r interaktive Kindergeschichten.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.9.7
  firebase_auth: ^0.6.2+1
  connectivity: ^0.4.3+1
  path_provider: ^1.1.0
  http: ^0.12.0+2

dev_dependencies:
  image_test_utils: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito:

flutter:
  uses-material-design: true
  fonts:
    - family: IndieFlower
      fonts:
        - asset: assets/IndieFlower.ttf
    - family: PatrickHand
      fonts:
        - asset: assets/PatrickHand-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
          style: normal
        - asset: assets/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/Montserrat-Italic.ttf
          style: italic
        - asset: assets/Montserrat-BoldItalic.ttf
          style: italic
          weight: 600

  assets:
    - assets/images/cloud.png
    - assets/images/cloud_logout_w.png
    - assets/images/cloud_logout_m.png
    - assets/images/cloud_reset_w.png
    - assets/images/cloud_reset_m.png
    - assets/images/register_user_m.png
    - assets/images/register_user_w.png
    - assets/images/cloud_login.png
    - assets/images/world.png
    - assets/images/user_settings.png
    - assets/images/girl_0.png
    - assets/images/girl_1.png
    - assets/images/girl_2.png
    - assets/images/boy_0.png
    - assets/images/boy_1.png
    - assets/images/boy_2.png
    - assets/images/icon.png
    - assets/images/house.png
    - assets/images/logout.png
    - assets/images/user_images/hund_0.jpg
    - assets/images/user_images/hund_1.jpg
    - assets/images/user_images/hund_2.jpg
    - assets/images/user_images/hund_3.jpg
    - assets/images/user_images/hund_4.jpg
    - assets/images/user_images/hund_5.jpg
    - assets/images/user_images/hund_6.jpg
    - assets/images/user_images/hund_7.jpg

