name: hundetage
description: Eine App fÃ¼r interaktive Kindergeschichten.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  rect_getter: ^0.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.9.7
  firebase_storage: ^2.1.0+1
  path_provider: ^0.5.0+1
  firebase_auth: ^0.6.2+1

dev_dependencies:
  image_test_utils: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito:

flutter:
  uses-material-design: true
  assets:
    - images/symbol_m.png
    - images/symbol_w.png
    - images/symbol_m_b.png
    - images/symbol_w_b.png
    - images/icon.png
    - images/user_screen_top_image.png
    - images/user_images/fragezeichen.jpg
    - images/user_images/hund_0.jpg
    - images/user_images/hund_1.jpg
    - images/user_images/hund_2.jpg
    - images/user_images/hund_3.jpg
    - images/user_images/hund_4.jpg
    - images/user_images/hund_5.jpg
    - images/user_images/hund_6.jpg
    - images/user_images/hund_7.jpg